import type { NodeDefinition } from './types'

export const HttpRequestNode: NodeDefinition = {
  type: 'action.http_request',
  name: 'HTTP Request',
  category: 'action',
  description: 'Make HTTP requests with comprehensive support for methods, headers, query parameters, path parameters, and form data. Features configurable timeout and status validation for robust API interactions.',
  icon: 'Globe',
  color: '#3b82f6',
  properties: [
    {
      name: 'url',
      label: 'URL',
      type: 'string',
      required: true,
      description: 'The URL to send the request to',
      placeholder: 'https://api.example.com/endpoint',
      visibility: 'user-or-llm',
    },
    {
      name: 'method',
      label: 'Method',
      type: 'options',
      default: 'GET',
      description: 'HTTP method (GET, POST, PUT, PATCH, DELETE)',
      visibility: 'user-or-llm',
      options: [
        { label: 'GET', value: 'GET' },
        { label: 'POST', value: 'POST' },
        { label: 'PUT', value: 'PUT' },
        { label: 'DELETE', value: 'DELETE' },
        { label: 'PATCH', value: 'PATCH' },
      ],
    },
    { 
      name: 'headers', 
      label: 'Headers', 
      type: 'key-value', 
      description: 'HTTP headers to include',
      visibility: 'user-or-llm',
    },
    {
      name: 'body',
      label: 'Body',
      type: 'json',
      description: 'Request body (for POST, PUT, PATCH)',
      condition: { field: 'method', value: ['POST', 'PUT', 'PATCH'] },
      visibility: 'user-or-llm',
    },
    {
      name: 'params',
      label: 'Query Parameters',
      type: 'key-value',
      description: 'URL query parameters to append',
      visibility: 'user-or-llm',
    },
    {
      name: 'pathParams',
      label: 'Path Parameters',
      type: 'key-value',
      description: 'URL path parameters to replace (e.g., :id in /users/:id)',
      visibility: 'user-or-llm',
    },
    {
      name: 'formData',
      label: 'Form Data',
      type: 'key-value',
      description: 'Form data to send (will set appropriate Content-Type)',
      visibility: 'user-or-llm',
    },
    { 
      name: 'timeout', 
      label: 'Timeout (ms)', 
      type: 'number', 
      default: 300000,
      description: 'Request timeout in milliseconds (default: 300000 = 5 minutes)',
      visibility: 'user-only',
    },
    {
      name: 'retries',
      label: 'Retries',
      type: 'number',
      default: 0,
      description: 'Number of retry attempts for retryable failures (timeouts, 429, 5xx). Default: 0 (no retries).',
      visibility: 'hidden',
    },
    {
      name: 'retryDelayMs',
      label: 'Retry Delay (ms)',
      type: 'number',
      default: 500,
      description: 'Initial retry delay in milliseconds (default: 500)',
      visibility: 'hidden',
    },
    {
      name: 'retryMaxDelayMs',
      label: 'Retry Max Delay (ms)',
      type: 'number',
      default: 30000,
      description: 'Maximum delay between retries in milliseconds (default: 30000)',
      visibility: 'hidden',
    },
    {
      name: 'retryNonIdempotent',
      label: 'Retry Non-Idempotent',
      type: 'boolean',
      default: false,
      description: 'Allow retries for non-idempotent methods like POST/PATCH (may create duplicate requests).',
      visibility: 'hidden',
    }
  ],
  inputs: 1,
  outputs: 1,
  allowError: true,
}
