"""add_user_id_to_workflow

Revision ID: 30a4bba315f3
Revises: d4611bbdbd59
Create Date: 2026-05-13 21:39:38.683128

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "30a4bba315f3"
down_revision: str | None = "d4611bbdbd59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credential", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "credential", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("execution", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("executionlog", "level", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "executionlog", "timestamp", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.add_column("workflow", sa.Column("user_id", sa.UUID(), nullable=False))
    op.alter_column("workflow", "schema_version", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("workflow", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("workflow", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("workflow", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.create_foreign_key(None, "workflow", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow", type_="foreignkey")
    op.alter_column("workflow", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("workflow", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("workflow", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("workflow", "schema_version", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("workflow", "user_id")
    op.alter_column("user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("user", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "executionlog", "timestamp", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("executionlog", "level", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("execution", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("credential", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("credential", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###
