"""Add workflow position

Revision ID: 5f26da795d90
Revises: 6b87038a60b9
Create Date: 2026-05-15 08:44:22.417419

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5f26da795d90'
down_revision: str | None = '6b87038a60b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'position')
    # ### end Alembic commands ###
