"""add user_id to credential

Revision ID: 5fad5564b104
Revises: f6435ffc980d
Create Date: 2026-05-16 01:39:17.638881

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5fad5564b104'
down_revision: Union[str, None] = 'f6435ffc980d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'credential', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.drop_column('credential', 'user_id')
    # ### end Alembic commands ###
