"""Add folders

Revision ID: 6b87038a60b9
Revises: 978dbbccfb6b
Create Date: 2026-05-14 23:36:22.877124

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6b87038a60b9'
down_revision: Union[str, None] = '978dbbccfb6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workflow', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workflow', 'folder', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'folder_id')
    op.drop_table('folder')
    # ### end Alembic commands ###
