"""add execution and execution_log tables

Revision ID: 978dbbccfb6b
Revises: 30a4bba315f3
Create Date: 2026-05-13 22:45:10.283354

"""

from collections.abc import Sequence

revision: str = "978dbbccfb6b"
down_revision: str | None = "30a4bba315f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
