"""Add color to workflow

Revision ID: f6435ffc980d
Revises: 5f26da795d90
Create Date: 2026-05-15 12:33:25.234177

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f6435ffc980d'
down_revision: str | None = '5f26da795d90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('color', sa.String(), nullable=True))
    op.drop_constraint(op.f('workflow_folder_id_fkey'), 'workflow', type_='foreignkey')
    op.create_foreign_key(None, 'workflow', 'folder', ['folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_folder_id_fkey'), 'workflow', 'folder', ['folder_id'], ['id'], ondelete='SET NULL')
    op.drop_column('workflow', 'color')
    # ### end Alembic commands ###
